

#include "srp/sha2big.c"
#include "srp/cstr.c"
#include "srp/t_math.c" 
#include "srp/srp.c"
#include "srp/srp6_server.c"

#include "tommath_class.h"
#include "bncore.c"
#include "bn_mp_init.c"
#include "bn_mp_init_size.c"
#include "bn_mp_init_copy.c"
#include "bn_mp_clear.c"
#include "bn_mp_set_int.c"
#include "bn_mp_zero.c"
#include "bn_mp_clamp.c"
#include "bn_mp_mul_2d.c"
#include "bn_mp_grow.c"
#include "bn_mp_copy.c"
#include "bn_mp_lshd.c"
#include "bn_mp_rshd.c"
#include "bn_mp_cmp.c"
#include "bn_mp_cmp_mag.c"
#include "bn_mp_cmp_d.c"
#include "bn_mp_add.c"
#include "bn_mp_sub.c"
#include "bn_mp_mul.c"
#include "bn_mp_mod.c"
#include "bn_mp_mod_d.c"
#include "bn_mp_mod_2d.c"
#include "bn_mp_exch.c"
#include "bn_mp_div.c"
#include "bn_mp_div_2d.c"
#include "bn_mp_add_d.c"
#include "bn_mp_sub_d.c"
#include "bn_mp_mul_d.c"
#include "bn_mp_mulmod.c"
#include "bn_mp_exptmod.c"
#include "bn_mp_div_d.c"
#include "bn_prime_tab.c"
#include "bn_mp_prime_is_prime.c"
#include "bn_mp_prime_is_divisible.c"
#include "bn_mp_prime_miller_rabin.c"
#include "bn_mp_count_bits.c"
#include "bn_mp_unsigned_bin_size.c"
#include "bn_mp_read_unsigned_bin.c"
#include "bn_mp_to_unsigned_bin.c"
#include "bn_mp_toradix.c"
#include "bn_s_mp_add.c"
#include "bn_s_mp_sub.c"
#include "bn_mp_set.c"
#include "bn_mp_cnt_lsb.c"
#include "bn_mp_sqr.c"
#include "bn_mp_sqrmod.c"
#include "bn_mp_radix_smap.c"
#include "bn_reverse.c"
#include "bn_mp_clear_multi.c"
#include "bn_mp_abs.c"
#include "bn_mp_div_3.c"
#include "bn_mp_invmod.c"
#include "bn_mp_dr_is_modulus.c"
#include "bn_mp_reduce_is_2k.c"
#include "bn_mp_reduce_is_2k_l.c"
#include "bn_fast_s_mp_mul_digs.c"
#include "bn_s_mp_mul_digs.c"
#include "bn_fast_s_mp_sqr.c"
#include "bn_s_mp_sqr.c"
#include "bn_mp_karatsuba_mul.c"
#include "bn_mp_toom_mul.c"
#include "bn_mp_karatsuba_sqr.c"
#include "bn_mp_toom_sqr.c"
#include "bn_mp_exptmod_fast.c"
#include "bn_s_mp_exptmod.c"
#include "bn_mp_init_multi.c"
#include "bn_mp_div_2.c"
#include "bn_mp_mul_2.c"
#include "bn_mp_reduce_setup.c"
#include "bn_mp_reduce.c"
#include "bn_mp_montgomery_setup.c"
#include "bn_mp_montgomery_calc_normalization.c"
#include "bn_mp_montgomery_reduce.c"
#include "bn_mp_dr_setup.c"
#include "bn_mp_dr_reduce.c"
#include "bn_mp_reduce_2k_setup.c"
#include "bn_mp_reduce_2k.c"
#include "bn_mp_reduce_2k_setup_l.c"
#include "bn_mp_reduce_2k_l.c"
#include "bn_fast_mp_invmod.c"
#include "bn_mp_invmod_slow.c"
#include "bn_fast_mp_montgomery_reduce.c"
#include "bn_mp_2expt.c"
#include "bn_s_mp_mul_high_digs.c"
#include "bn_fast_s_mp_mul_high_digs.c"


void t_stronginitrand()
{
}

void t_random(char* data, unsigned size)
{
	memset(data, 0, size);
}

